set(SRC_FILES
    App.cpp
    MapManager.cpp
    Character.cpp
    MovingPlatform.cpp
)

set(INCLUDE_FILES
    App.hpp
    Block.hpp
    MapManager.hpp
    Mario.hpp
    Character.hpp
    Breakableblock.hpp
    QuestionBlock.hpp
    Unbreakableblock.hpp
    Coin.hpp
    FireFlower.hpp
    GameStateManager.hpp
    Koopa.hpp
    PiranhaPlant.hpp
    OneUp.hpp
    SuperStar.hpp
    MovingPlatform.hpp
    SFXManager.hpp
    BGMManager.hpp
)

set(TEST_FILES
)
